def main():
    for i in range(1,65):
        print("insert into Competitions (event_id, category_id, round_def_id) values ('1', '" + str(i) + "', '" + str(findRoundDefID(i)) + "');")
    for i in range(1,65):
        print("insert into EquivalentRounds (equivalent_category_id, equivalent_round_def_id, date_from,date_to, base_round_def_id) values ('"
              + str(i) + "', '" + str(findRoundDefID(i)) + "', '2017-01-01', NULL, '1');")
            
def findRoundDefID(category_id): #returns the correct round_def_id based on a given category_id
    match(category_id):
        case 1:
            return 1
        case 2:
            return 1
        case 3:
            return 2
        case 4:
            return 3
        case 5:
            return 2
        case 6:
            return 2
        case 7:
            return 3
        case 8:
            return 4
        case 9:
            return 2
        case 10:
            return 2
        case 11:
            return 3
        case 12:
            return 4
        case 13:
            return 3
        case 14:
            return 3
        case 15:
            return 3
        case 16:
            return 4
        case 17:
            return 3
        case 18:
            return 3
        case 19:
            return 3
        case 20:
            return 4
        case 21:
            return 4
        case 22:
            return 4
        case 23:
            return 4
        case 24:
            return 4
        case 25:
            return 3
        case 26:
            return 3
        case 27:
            return 3
        case 28:
            return 4
        case 29:
            return 4
        case 30:
            return 4
        case 31:
            return 4
        case 32:
            return 4
        case 33:
            return 1
        case 34:
            return 1
        case 35:
            return 2
        case 36:
            return 3
        case 37:
            return 2
        case 38:
            return 2
        case 39:
            return 3
        case 40:
            return 4
        case 41:
            return 2
        case 42:
            return 2
        case 43:
            return 3
        case 44:
            return 4
        case 45:
            return 3
        case 46:
            return 3
        case 47:
            return 4
        case 48:
            return 4
        case 49:
            return 4
        case 50:
            return 4
        case 51:
            return 5
        case 52:
            return 5
        case 53:
            return 4
        case 54:
            return 4
        case 55:
            return 5
        case 56:
            return 5
        case 57:
            return 5
        case 58:
            return 5
        case 59:
            return 5
        case 60:
            return 5
        case 61:
            return 5
        case 62:
            return 5
        case 63:
            return 5
        case 64:
            return 5
        
if __name__ == "__main__":
    main()