insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('3', 'Titos', 'Van Niekerk', 'M', '1942');
insert into UserAccounts(user_id, user_password, is_recorder) values ('3', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('4', 'Duncan', 'Riccard', 'M', '1970');
insert into UserAccounts(user_id, user_password, is_recorder) values ('4', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('5', 'Caspar', 'Buffy', 'M', '1998');
insert into UserAccounts(user_id, user_password, is_recorder) values ('5', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('6', 'Tracy', 'Moorhead', 'M', '1964');
insert into UserAccounts(user_id, user_password, is_recorder) values ('6', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('7', 'Tobey', 'Frean', 'F', '1968');
insert into UserAccounts(user_id, user_password, is_recorder) values ('7', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('8', 'Anabelle', 'Crawcour', 'F', '1965');
insert into UserAccounts(user_id, user_password, is_recorder) values ('8', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('9', 'Patten', 'Deble', 'M', '1947');
insert into UserAccounts(user_id, user_password, is_recorder) values ('9', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('10', 'Koralle', 'Shatliffe', 'F', '1980');
insert into UserAccounts(user_id, user_password, is_recorder) values ('10', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('11', 'Jere', 'Iannitti', 'F', '2007');
insert into UserAccounts(user_id, user_password, is_recorder) values ('11', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('12', 'Case', 'Norwell', 'M', '1965');
insert into UserAccounts(user_id, user_password, is_recorder) values ('12', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('13', 'Kaspar', 'Ternouth', 'M', '1956');
insert into UserAccounts(user_id, user_password, is_recorder) values ('13', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('14', 'Isac', 'MacGuiness', 'M', '1982');
insert into UserAccounts(user_id, user_password, is_recorder) values ('14', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('15', 'Andris', 'Bernetti', 'M', '1946');
insert into UserAccounts(user_id, user_password, is_recorder) values ('15', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('16', 'Maryjo', 'Rossander', 'F', '1972');
insert into UserAccounts(user_id, user_password, is_recorder) values ('16', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('17', 'Si', 'Grabb', 'M', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('17', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('18', 'Claudius', 'Christopherson', 'M', '1954');
insert into UserAccounts(user_id, user_password, is_recorder) values ('18', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('19', 'Aldin', 'Jewess', 'M', '2000');
insert into UserAccounts(user_id, user_password, is_recorder) values ('19', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('20', 'Melisandra', 'Harriskine', 'F', '1944');
insert into UserAccounts(user_id, user_password, is_recorder) values ('20', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('21', 'Dasha', 'Dudhill', 'F', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('21', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('22', 'Issie', 'Willoughby', 'F', '1946');
insert into UserAccounts(user_id, user_password, is_recorder) values ('22', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('23', 'Abagail', 'Sailor', 'F', '1959');
insert into UserAccounts(user_id, user_password, is_recorder) values ('23', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('24', 'Kean', 'Matveichev', 'M', '1957');
insert into UserAccounts(user_id, user_password, is_recorder) values ('24', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('25', 'Lynn', 'Kohnemann', 'F', '1993');
insert into UserAccounts(user_id, user_password, is_recorder) values ('25', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('26', 'Elena', 'Bernli', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('26', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('27', 'Lucas', 'Neal', 'M', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('27', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('28', 'Toinette', 'Firmin', 'F', '1968');
insert into UserAccounts(user_id, user_password, is_recorder) values ('28', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('29', 'Farrell', 'Gladeche', 'M', '1953');
insert into UserAccounts(user_id, user_password, is_recorder) values ('29', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('30', 'Wyndham', 'Poley', 'M', '1950');
insert into UserAccounts(user_id, user_password, is_recorder) values ('30', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('31', 'Gamaliel', 'Lehr', 'M', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('31', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('32', 'Ettie', 'Sinderland', 'F', '1959');
insert into UserAccounts(user_id, user_password, is_recorder) values ('32', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('33', 'Jillana', 'Chimes', 'F', '1979');
insert into UserAccounts(user_id, user_password, is_recorder) values ('33', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('34', 'Amelia', 'MacKeogh', 'F', '2001');
insert into UserAccounts(user_id, user_password, is_recorder) values ('34', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('35', 'Kurt', 'Dufore', 'M', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('35', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('36', 'Kally', 'Witcomb', 'F', '1966');
insert into UserAccounts(user_id, user_password, is_recorder) values ('36', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('37', 'Joaquin', 'Irvine', 'M', '1970');
insert into UserAccounts(user_id, user_password, is_recorder) values ('37', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('38', 'Mahmud', 'Sutcliffe', 'M', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('38', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('39', 'Lion', 'McConnachie', 'M', '1981');
insert into UserAccounts(user_id, user_password, is_recorder) values ('39', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('40', 'Rodina', 'Spain-Gower', 'F', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('40', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('41', 'Josefa', 'Plank', 'F', '2002');
insert into UserAccounts(user_id, user_password, is_recorder) values ('41', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('42', 'Onofredo', 'Drewry', 'M', '1989');
insert into UserAccounts(user_id, user_password, is_recorder) values ('42', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('43', 'Markus', 'Barltrop', 'M', '1963');
insert into UserAccounts(user_id, user_password, is_recorder) values ('43', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('44', 'Mischa', 'Oland', 'M', '1973');
insert into UserAccounts(user_id, user_password, is_recorder) values ('44', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('45', 'Reina', 'Van Oort', 'F', '1988');
insert into UserAccounts(user_id, user_password, is_recorder) values ('45', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('46', 'Stillmann', 'Getcliffe', 'M', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('46', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('47', 'Clovis', 'Ebdon', 'F', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('47', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('48', 'Jacklyn', 'Durbridge', 'F', '1992');
insert into UserAccounts(user_id, user_password, is_recorder) values ('48', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('49', 'Anneliese', 'Bruhnicke', 'F', '1990');
insert into UserAccounts(user_id, user_password, is_recorder) values ('49', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('50', 'Andee', 'Schapero', 'F', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('50', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('51', 'Sebastien', 'Obeney', 'M', '2011');
insert into UserAccounts(user_id, user_password, is_recorder) values ('51', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('52', 'Taylor', 'Lavrick', 'M', '1952');
insert into UserAccounts(user_id, user_password, is_recorder) values ('52', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('53', 'Pete', 'Clarricoates', 'M', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('53', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('54', 'Dory', 'Shorey', 'M', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('54', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('55', 'Delainey', 'Otterwell', 'M', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('55', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('56', 'Coop', 'Gellert', 'M', '1979');
insert into UserAccounts(user_id, user_password, is_recorder) values ('56', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('57', 'Westbrooke', 'Fader', 'M', '1947');
insert into UserAccounts(user_id, user_password, is_recorder) values ('57', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('58', 'Josie', 'Leuty', 'F', '1989');
insert into UserAccounts(user_id, user_password, is_recorder) values ('58', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('59', 'Lorin', 'Broadhurst', 'M', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('59', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('60', 'Pauline', 'McCaghan', 'F', '1947');
insert into UserAccounts(user_id, user_password, is_recorder) values ('60', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('61', 'Bradney', 'Peepall', 'M', '2012');
insert into UserAccounts(user_id, user_password, is_recorder) values ('61', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('62', 'Karita', 'Sinncock', 'F', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('62', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('63', 'Micky', 'Masselin', 'M', '1973');
insert into UserAccounts(user_id, user_password, is_recorder) values ('63', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('64', 'Christie', 'OLoghlen', 'F', '2001');
insert into UserAccounts(user_id, user_password, is_recorder) values ('64', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('65', 'Devlin', 'Wareham', 'M', '1999');
insert into UserAccounts(user_id, user_password, is_recorder) values ('65', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('66', 'Emelina', 'Trollope', 'F', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('66', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('67', 'Domini', 'Lapwood', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('67', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('68', 'Gaylord', 'Taunton.', 'M', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('68', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('69', 'Lela', 'Margerison', 'F', '2012');
insert into UserAccounts(user_id, user_password, is_recorder) values ('69', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('70', 'Moll', 'Potte', 'F', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('70', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('71', 'Lori', 'Keatch', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('71', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('72', 'Lalo', 'Pechacek', 'M', '1953');
insert into UserAccounts(user_id, user_password, is_recorder) values ('72', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('73', 'Genvieve', 'Castellan', 'F', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('73', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('74', 'Gabbey', 'Volks', 'F', '1986');
insert into UserAccounts(user_id, user_password, is_recorder) values ('74', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('75', 'Kerwin', 'McAvin', 'M', '1941');
insert into UserAccounts(user_id, user_password, is_recorder) values ('75', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('76', 'Pearce', 'Palia', 'M', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('76', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('77', 'Lucas', 'Luffman', 'M', '2013');
insert into UserAccounts(user_id, user_password, is_recorder) values ('77', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('78', 'Dru', 'Greenacre', 'M', '1990');
insert into UserAccounts(user_id, user_password, is_recorder) values ('78', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('79', 'Wilfrid', 'Alleway', 'M', '1987');
insert into UserAccounts(user_id, user_password, is_recorder) values ('79', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('80', 'Ban', 'Yarham', 'M', '1944');
insert into UserAccounts(user_id, user_password, is_recorder) values ('80', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('81', 'Purcell', 'Wilshire', 'M', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('81', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('82', 'Gregor', 'Duchenne', 'M', '1983');
insert into UserAccounts(user_id, user_password, is_recorder) values ('82', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('83', 'Fawn', 'Haycock', 'F', '1977');
insert into UserAccounts(user_id, user_password, is_recorder) values ('83', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('84', 'Morissa', 'Brahms', 'F', '1987');
insert into UserAccounts(user_id, user_password, is_recorder) values ('84', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('85', 'Elysia', 'Chesser', 'F', '1984');
insert into UserAccounts(user_id, user_password, is_recorder) values ('85', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('86', 'Drud', 'Rupel', 'M', '1967');
insert into UserAccounts(user_id, user_password, is_recorder) values ('86', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('87', 'Abbott', 'Anscombe', 'M', '1971');
insert into UserAccounts(user_id, user_password, is_recorder) values ('87', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('88', 'Tracey', 'MacNeish', 'M', '1974');
insert into UserAccounts(user_id, user_password, is_recorder) values ('88', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('89', 'Alastair', 'Grancher', 'M', '1942');
insert into UserAccounts(user_id, user_password, is_recorder) values ('89', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('90', 'Nikaniki', 'Ruppel', 'F', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('90', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('91', 'Ardeen', 'Demongeot', 'F', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('91', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('92', 'Verge', 'Deftie', 'M', '1991');
insert into UserAccounts(user_id, user_password, is_recorder) values ('92', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('93', 'Nick', 'Christie', 'M', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('93', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('94', 'Judd', 'Keenleyside', 'M', '1998');
insert into UserAccounts(user_id, user_password, is_recorder) values ('94', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('95', 'Melisandra', 'Lighterness', 'F', '1969');
insert into UserAccounts(user_id, user_password, is_recorder) values ('95', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('96', 'Corbie', 'Woolen', 'M', '1994');
insert into UserAccounts(user_id, user_password, is_recorder) values ('96', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('97', 'Lana', 'Taveriner', 'F', '1994');
insert into UserAccounts(user_id, user_password, is_recorder) values ('97', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('98', 'Markos', 'Castro', 'M', '1990');
insert into UserAccounts(user_id, user_password, is_recorder) values ('98', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('99', 'Parsifal', 'Cumpsty', 'M', '1959');
insert into UserAccounts(user_id, user_password, is_recorder) values ('99', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('100', 'Carly', 'Penhall', 'F', '1953');
insert into UserAccounts(user_id, user_password, is_recorder) values ('100', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('101', 'Rollin', 'Signorelli', 'M', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('101', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('102', 'Cesya', 'Brower', 'F', '2003');
insert into UserAccounts(user_id, user_password, is_recorder) values ('102', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('103', 'Clarie', 'Philipard', 'F', '1974');
insert into UserAccounts(user_id, user_password, is_recorder) values ('103', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('104', 'Oralle', 'Boycott', 'F', '2006');
insert into UserAccounts(user_id, user_password, is_recorder) values ('104', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('105', 'Munroe', 'Ganing', 'M', '1952');
insert into UserAccounts(user_id, user_password, is_recorder) values ('105', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('106', 'Hallie', 'Claiton', 'F', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('106', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('107', 'Ginnie', 'Febry', 'F', '1981');
insert into UserAccounts(user_id, user_password, is_recorder) values ('107', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('108', 'Helen-elizabeth', 'Van Dalen', 'F', '1990');
insert into UserAccounts(user_id, user_password, is_recorder) values ('108', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('109', 'Brice', 'Bolt', 'M', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('109', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('110', 'Binni', 'Strathe', 'F', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('110', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('111', 'Ari', 'Klimko', 'M', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('111', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('112', 'Lonnie', 'Ludford', 'M', '2007');
insert into UserAccounts(user_id, user_password, is_recorder) values ('112', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('113', 'Whitney', 'Spreull', 'F', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('113', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('114', 'Malchy', 'Gilsthorpe', 'M', '1955');
insert into UserAccounts(user_id, user_password, is_recorder) values ('114', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('115', 'Novelia', 'Westwick', 'F', '1971');
insert into UserAccounts(user_id, user_password, is_recorder) values ('115', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('116', 'Elihu', 'Edens', 'M', '1957');
insert into UserAccounts(user_id, user_password, is_recorder) values ('116', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('117', 'Jefferey', 'Raynes', 'M', '2006');
insert into UserAccounts(user_id, user_password, is_recorder) values ('117', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('118', 'Sascha', 'McFall', 'M', '1946');
insert into UserAccounts(user_id, user_password, is_recorder) values ('118', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('119', 'Flora', 'Damrell', 'F', '1991');
insert into UserAccounts(user_id, user_password, is_recorder) values ('119', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('120', 'Luke', 'Fancy', 'M', '1982');
insert into UserAccounts(user_id, user_password, is_recorder) values ('120', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('121', 'Devi', 'Sapsforde', 'F', '1953');
insert into UserAccounts(user_id, user_password, is_recorder) values ('121', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('122', 'Isak', 'Wagner', 'M', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('122', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('123', 'Berne', 'Saing', 'M', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('123', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('124', 'Berny', 'Tireman', 'M', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('124', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('125', 'Simona', 'Tatteshall', 'F', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('125', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('126', 'Aleksandr', 'Filson', 'M', '1961');
insert into UserAccounts(user_id, user_password, is_recorder) values ('126', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('127', 'Nathanil', 'Verdey', 'M', '1966');
insert into UserAccounts(user_id, user_password, is_recorder) values ('127', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('128', 'Brigham', 'Ivkovic', 'M', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('128', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('129', 'Ciel', 'Edmund', 'F', '1940');
insert into UserAccounts(user_id, user_password, is_recorder) values ('129', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('130', 'Britt', 'Aubrun', 'F', '1974');
insert into UserAccounts(user_id, user_password, is_recorder) values ('130', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('131', 'Lyssa', 'Ridgwell', 'F', '1979');
insert into UserAccounts(user_id, user_password, is_recorder) values ('131', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('132', 'Cristal', 'Rapier', 'F', '1971');
insert into UserAccounts(user_id, user_password, is_recorder) values ('132', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('133', 'Georgina', 'Nangle', 'F', '1941');
insert into UserAccounts(user_id, user_password, is_recorder) values ('133', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('134', 'Rosamond', 'MacTrustie', 'F', '1993');
insert into UserAccounts(user_id, user_password, is_recorder) values ('134', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('135', 'Aurthur', 'Graves', 'M', '1997');
insert into UserAccounts(user_id, user_password, is_recorder) values ('135', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('136', 'Marten', 'Sherel', 'M', '1965');
insert into UserAccounts(user_id, user_password, is_recorder) values ('136', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('137', 'Dulcinea', 'Revens', 'F', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('137', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('138', 'Laughton', 'Kusick', 'M', '1947');
insert into UserAccounts(user_id, user_password, is_recorder) values ('138', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('139', 'Elsworth', 'Crehan', 'M', '1957');
insert into UserAccounts(user_id, user_password, is_recorder) values ('139', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('140', 'Carita', 'Sandry', 'F', '1950');
insert into UserAccounts(user_id, user_password, is_recorder) values ('140', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('141', 'Gardiner', 'Hrishchenko', 'M', '1957');
insert into UserAccounts(user_id, user_password, is_recorder) values ('141', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('142', 'Catharine', 'Warbey', 'F', '1993');
insert into UserAccounts(user_id, user_password, is_recorder) values ('142', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('143', 'Dulsea', 'Grzesiewicz', 'F', '2013');
insert into UserAccounts(user_id, user_password, is_recorder) values ('143', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('144', 'Troy', 'Lavington', 'M', '1962');
insert into UserAccounts(user_id, user_password, is_recorder) values ('144', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('145', 'Loy', 'Weekley', 'M', '1989');
insert into UserAccounts(user_id, user_password, is_recorder) values ('145', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('146', 'Rozalin', 'Kytter', 'F', '1946');
insert into UserAccounts(user_id, user_password, is_recorder) values ('146', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('147', 'Gustaf', 'Hansana', 'M', '1990');
insert into UserAccounts(user_id, user_password, is_recorder) values ('147', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('148', 'Gawen', 'Prier', 'M', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('148', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('149', 'Renato', 'Skeldinge', 'M', '1944');
insert into UserAccounts(user_id, user_password, is_recorder) values ('149', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('150', 'Alika', 'Clowsley', 'F', '1975');
insert into UserAccounts(user_id, user_password, is_recorder) values ('150', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('151', 'Erie', 'Sturgeon', 'M', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('151', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('152', 'Kelsey', 'Mollin', 'M', '1969');
insert into UserAccounts(user_id, user_password, is_recorder) values ('152', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('153', 'Mari', 'Tippler', 'F', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('153', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('154', 'Kasey', 'Lardeux', 'F', '2003');
insert into UserAccounts(user_id, user_password, is_recorder) values ('154', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('155', 'Neddy', 'Cricket', 'M', '1942');
insert into UserAccounts(user_id, user_password, is_recorder) values ('155', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('156', 'Garwin', 'Radolf', 'M', '1962');
insert into UserAccounts(user_id, user_password, is_recorder) values ('156', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('157', 'Collete', 'Geater', 'F', '2005');
insert into UserAccounts(user_id, user_password, is_recorder) values ('157', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('158', 'Clare', 'Holme', 'M', '1941');
insert into UserAccounts(user_id, user_password, is_recorder) values ('158', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('159', 'Val', 'Choupin', 'F', '1986');
insert into UserAccounts(user_id, user_password, is_recorder) values ('159', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('160', 'Tiffani', 'Welton', 'F', '1949');
insert into UserAccounts(user_id, user_password, is_recorder) values ('160', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('161', 'Anna-maria', 'Newbigging', 'F', '1991');
insert into UserAccounts(user_id, user_password, is_recorder) values ('161', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('162', 'Conrad', 'Taillant', 'M', '1986');
insert into UserAccounts(user_id, user_password, is_recorder) values ('162', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('163', 'Etti', 'Yardley', 'F', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('163', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('164', 'Joannes', 'Maddison', 'F', '1964');
insert into UserAccounts(user_id, user_password, is_recorder) values ('164', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('165', 'Ermanno', 'Jacquot', 'M', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('165', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('166', 'Stearne', 'Drogan', 'M', '1968');
insert into UserAccounts(user_id, user_password, is_recorder) values ('166', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('167', 'Clea', 'Atlay', 'F', '2002');
insert into UserAccounts(user_id, user_password, is_recorder) values ('167', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('168', 'Mikel', 'Galvan', 'M', '2006');
insert into UserAccounts(user_id, user_password, is_recorder) values ('168', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('169', 'Cordie', 'McPartling', 'F', '1981');
insert into UserAccounts(user_id, user_password, is_recorder) values ('169', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('170', 'Pippo', 'Hatfull', 'M', '1971');
insert into UserAccounts(user_id, user_password, is_recorder) values ('170', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('171', 'Joann', 'Ebunoluwa', 'F', '1950');
insert into UserAccounts(user_id, user_password, is_recorder) values ('171', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('172', 'Lilas', 'Della Scala', 'F', '1985');
insert into UserAccounts(user_id, user_password, is_recorder) values ('172', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('173', 'Abe', 'Demonge', 'M', '2008');
insert into UserAccounts(user_id, user_password, is_recorder) values ('173', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('174', 'Christoper', 'Handy', 'M', '2007');
insert into UserAccounts(user_id, user_password, is_recorder) values ('174', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('175', 'Tressa', 'Maryon', 'F', '1969');
insert into UserAccounts(user_id, user_password, is_recorder) values ('175', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('176', 'Lexie', 'Chatband', 'F', '1985');
insert into UserAccounts(user_id, user_password, is_recorder) values ('176', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('177', 'Vilma', 'Feldman', 'F', '1943');
insert into UserAccounts(user_id, user_password, is_recorder) values ('177', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('178', 'Harris', 'Peasee', 'M', '2003');
insert into UserAccounts(user_id, user_password, is_recorder) values ('178', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('179', 'Augustine', 'Yonnie', 'F', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('179', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('180', 'Stephanus', 'Windows', 'M', '1975');
insert into UserAccounts(user_id, user_password, is_recorder) values ('180', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('181', 'Granny', 'Moggie', 'M', '1964');
insert into UserAccounts(user_id, user_password, is_recorder) values ('181', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('182', 'Elihu', 'Gomme', 'M', '1963');
insert into UserAccounts(user_id, user_password, is_recorder) values ('182', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('183', 'Yoko', 'Lakeland', 'F', '1981');
insert into UserAccounts(user_id, user_password, is_recorder) values ('183', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('184', 'Willabella', 'Streight', 'F', '1946');
insert into UserAccounts(user_id, user_password, is_recorder) values ('184', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('185', 'Audrie', 'Lerhinan', 'F', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('185', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('186', 'Nappy', 'Maggs', 'M', '2008');
insert into UserAccounts(user_id, user_password, is_recorder) values ('186', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('187', 'Ambrosius', 'Plester', 'M', '2004');
insert into UserAccounts(user_id, user_password, is_recorder) values ('187', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('188', 'Frederigo', 'Auchinleck', 'M', '1973');
insert into UserAccounts(user_id, user_password, is_recorder) values ('188', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('189', 'Linn', 'Brindley', 'F', '1983');
insert into UserAccounts(user_id, user_password, is_recorder) values ('189', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('190', 'Jannelle', 'Hayward', 'F', '2000');
insert into UserAccounts(user_id, user_password, is_recorder) values ('190', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('191', 'Saidee', 'Heather', 'F', '1980');
insert into UserAccounts(user_id, user_password, is_recorder) values ('191', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('192', 'Rebekah', 'Mokes', 'F', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('192', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('193', 'Andee', 'Ducker', 'F', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('193', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('194', 'Buddie', 'Bewlay', 'M', '2003');
insert into UserAccounts(user_id, user_password, is_recorder) values ('194', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('195', 'Isacco', 'Mackerel', 'M', '2009');
insert into UserAccounts(user_id, user_password, is_recorder) values ('195', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('196', 'Kikelia', 'Clayson', 'F', '1944');
insert into UserAccounts(user_id, user_password, is_recorder) values ('196', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('197', 'Demetris', 'Eberdt', 'M', '1966');
insert into UserAccounts(user_id, user_password, is_recorder) values ('197', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('198', 'Joanne', 'Jolliff', 'F', '2008');
insert into UserAccounts(user_id, user_password, is_recorder) values ('198', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('199', 'Kerrill', 'McNab', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('199', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('200', 'Allissa', 'Baptiste', 'F', '1973');
insert into UserAccounts(user_id, user_password, is_recorder) values ('200', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('201', 'Milo', 'Whewell', 'M', '1943');
insert into UserAccounts(user_id, user_password, is_recorder) values ('201', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('202', 'Glenine', 'Bunch', 'F', '1967');
insert into UserAccounts(user_id, user_password, is_recorder) values ('202', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('203', 'Irving', 'Kidsley', 'M', '1951');
insert into UserAccounts(user_id, user_password, is_recorder) values ('203', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('204', 'Pearline', 'Lipman', 'F', '1953');
insert into UserAccounts(user_id, user_password, is_recorder) values ('204', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('205', 'Dagmar', 'Bruhnicke', 'F', '1984');
insert into UserAccounts(user_id, user_password, is_recorder) values ('205', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('206', 'Evaleen', 'Belden', 'F', '1973');
insert into UserAccounts(user_id, user_password, is_recorder) values ('206', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('207', 'Mabelle', 'Fredson', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('207', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('208', 'Vanya', 'Mingaye', 'F', '1986');
insert into UserAccounts(user_id, user_password, is_recorder) values ('208', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('209', 'Stanton', 'Armitt', 'M', '1979');
insert into UserAccounts(user_id, user_password, is_recorder) values ('209', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('210', 'Nomi', 'Schwanden', 'F', '2000');
insert into UserAccounts(user_id, user_password, is_recorder) values ('210', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('211', 'Celinka', 'Greenier', 'F', '2005');
insert into UserAccounts(user_id, user_password, is_recorder) values ('211', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('212', 'Sayers', 'Normavell', 'M', '1988');
insert into UserAccounts(user_id, user_password, is_recorder) values ('212', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('213', 'Sallyanne', 'Shovelbottom', 'F', '2002');
insert into UserAccounts(user_id, user_password, is_recorder) values ('213', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('214', 'Terra', 'Stent', 'F', '1996');
insert into UserAccounts(user_id, user_password, is_recorder) values ('214', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('215', 'Camille', 'Setterington', 'F', '1959');
insert into UserAccounts(user_id, user_password, is_recorder) values ('215', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('216', 'Umberto', 'Siburn', 'M', '1980');
insert into UserAccounts(user_id, user_password, is_recorder) values ('216', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('217', 'Ezechiel', 'Likely', 'M', '1948');
insert into UserAccounts(user_id, user_password, is_recorder) values ('217', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('218', 'Stu', 'Holburn', 'M', '1960');
insert into UserAccounts(user_id, user_password, is_recorder) values ('218', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('219', 'Fancie', 'de Mendoza', 'F', '1968');
insert into UserAccounts(user_id, user_password, is_recorder) values ('219', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('220', 'Josh', 'Asty', 'M', '2000');
insert into UserAccounts(user_id, user_password, is_recorder) values ('220', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('221', 'Sela', 'Kimberly', 'F', '1995');
insert into UserAccounts(user_id, user_password, is_recorder) values ('221', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('222', 'Tudor', 'Merigon', 'M', '2000');
insert into UserAccounts(user_id, user_password, is_recorder) values ('222', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('223', 'Kincaid', 'Fumagall', 'M', '1940');
insert into UserAccounts(user_id, user_password, is_recorder) values ('223', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('224', 'Ally', 'Pinch', 'F', '1993');
insert into UserAccounts(user_id, user_password, is_recorder) values ('224', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('225', 'Libby', 'Vautrey', 'F', '1955');
insert into UserAccounts(user_id, user_password, is_recorder) values ('225', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('226', 'Kelly', 'Smallman', 'F', '1983');
insert into UserAccounts(user_id, user_password, is_recorder) values ('226', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('227', 'Vernen', 'Pidgin', 'M', '1958');
insert into UserAccounts(user_id, user_password, is_recorder) values ('227', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('228', 'Charlena', 'Ballay', 'F', '1978');
insert into UserAccounts(user_id, user_password, is_recorder) values ('228', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('229', 'Kathi', 'Jozaitis', 'F', '1993');
insert into UserAccounts(user_id, user_password, is_recorder) values ('229', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('230', 'Ginny', 'Wing', 'F', '2011');
insert into UserAccounts(user_id, user_password, is_recorder) values ('230', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('231', 'Gardiner', 'Killner', 'M', '1984');
insert into UserAccounts(user_id, user_password, is_recorder) values ('231', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('232', 'Mindy', 'Syvret', 'F', '1999');
insert into UserAccounts(user_id, user_password, is_recorder) values ('232', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('233', 'Dermot', 'Trevains', 'M', '1941');
insert into UserAccounts(user_id, user_password, is_recorder) values ('233', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('234', 'Farand', 'Borman', 'F', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('234', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('235', 'Paola', 'Antonignetti', 'F', '1945');
insert into UserAccounts(user_id, user_password, is_recorder) values ('235', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('236', 'Cecile', 'Dessant', 'F', '1985');
insert into UserAccounts(user_id, user_password, is_recorder) values ('236', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('237', 'Loutitia', 'Wittering', 'F', '1989');
insert into UserAccounts(user_id, user_password, is_recorder) values ('237', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('238', 'Tabatha', 'Sandwick', 'F', '1984');
insert into UserAccounts(user_id, user_password, is_recorder) values ('238', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('239', 'Heidie', 'Ripping', 'F', '1980');
insert into UserAccounts(user_id, user_password, is_recorder) values ('239', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('240', 'Turner', 'Yemm', 'M', '1987');
insert into UserAccounts(user_id, user_password, is_recorder) values ('240', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('241', 'Gerald', 'MacGorman', 'M', '1977');
insert into UserAccounts(user_id, user_password, is_recorder) values ('241', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('242', 'Britni', 'Skewes', 'F', '1982');
insert into UserAccounts(user_id, user_password, is_recorder) values ('242', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('243', 'Brittne', 'Steagall', 'F', '2005');
insert into UserAccounts(user_id, user_password, is_recorder) values ('243', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('244', 'Ginelle', 'Caller', 'F', '2010');
insert into UserAccounts(user_id, user_password, is_recorder) values ('244', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('245', 'Michale', 'Ridder', 'M', '1952');
insert into UserAccounts(user_id, user_password, is_recorder) values ('245', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('246', 'Zacherie', 'Seint', 'M', '1954');
insert into UserAccounts(user_id, user_password, is_recorder) values ('246', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('247', 'Casey', 'Siveyer', 'M', '1955');
insert into UserAccounts(user_id, user_password, is_recorder) values ('247', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('248', 'Avie', 'Channer', 'F', '1962');
insert into UserAccounts(user_id, user_password, is_recorder) values ('248', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('249', 'Dallas', 'Sarath', 'F', '1965');
insert into UserAccounts(user_id, user_password, is_recorder) values ('249', 'password', '0');
insert into Archers (archer_id, archer_firstname, archer_lastname, archer_gender, archer_birthyear) values ('250', 'Audy', 'Swaby', 'F', '1989');
insert into UserAccounts(user_id, user_password, is_recorder) values ('250', 'password', '0');
